name: Wingman Autonomy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    name: Apply chezmoi on server
    runs-on: [self-hosted, pegasus]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.WINGMAN_DEPLOY_KEY }}

      - name: Run chezmoi apply remotely
        run: ssh -o StrictHostKeyChecking=no wingman@198.96.88.177 "cd ~/.local/share/chezmoi && git pull && chezmoi apply --verbose"
